# Setup
title: Hsiao78611
description: 突然發現沒有紀錄點東西<br/>要讓人認識你會變得相當困難
url: https://hsiao78611.github.io
avatar: /images/avatar.jpeg
paginate: 5
permalink: pretty
cover_image: /images/bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec
  - vendor/

# Optimize Jekyl SEO Tag
twitter:
  username: Hsiao78611
  card: summary
logo: logo.png
social:
  name: Hsiao78611
  links:
    - https://twitter.com/hsiao78611
    - https://github.com/hsiao78611
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Hsiao78611
  url: https://github.com/hsiao78611/
  email: hsiao78611@gmail.com
